package com.sampleapp;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
@SpringBootApplication
public class SampleApplicationMain {

    private static final Logger LOGGER = LoggerFactory.getLogger(SampleApplicationMain.class);

    public static void main(String[] args) {
        LOGGER.info("Starting Spring Boot application - START");

        SpringApplication.run(SampleApplicationMain.class, args);

        LOGGER.info("Starting Spring Boot application - END");
    }
}
