package london.dragu.matei.java.http.rest.sample;

import lombok.extern.slf4j.Slf4j;
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
@SpringBootApplication
@Slf4j
public class SampleApplicationMain {

    public static void main(String[] args) {
        log.info("Starting Spring Boot application - START");

        SpringApplication.run(SampleApplicationMain.class, args);

        log.info("Starting Spring Boot application - END");
    }
}
